apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: manifest-editor
  namespace: {{ .Release.Namespace }}
spec:
  gateways:
    - teknoir/teknoir-gateway
  hosts:
    - '*'
  http:
    - match:
        - uri:
            prefix: "{{ .Values.basePath }}/manifest-editor"
      route:
        - destination:
            host: manifest-editor.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 80
