apiVersion: v1
kind: Service
metadata:
  name: manifest-editor
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    application: manifest-editor
  ports:
    - name: http
      port: 80
      targetPort: 8000