---
apiVersion: v1
kind: Secret
metadata:
  name: re-id-mongo
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: {{ .Values.mongo.auth.username | quote }}
  password: {{ .Values.mongo.auth.password | quote }}
  uri: {{ printf "mongodb://%s:%s@re-id-mongo:%.0f" .Values.mongo.auth.username .Values.mongo.auth.password .Values.mongo.service.port | quote }}
