apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: re-id-mongo
spec:
  serviceName: "re-id-mongo"
  replicas: 1
  selector:
    matchLabels:
      app: re-id-mongo
  template:
    metadata:
      labels:
        app: re-id-mongo
    spec:
      containers:
      - name: mongo
        image: "{{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag }}"
        imagePullPolicy: {{ .Values.mongo.image.pullPolicy }}
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: re-id-mongo
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: re-id-mongo
              key: password
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: re-id-mongo
