apiVersion: v1
kind: Secret
metadata:
  name: re-id-mongo
type: Opaque
data:
  username: {{ .Values.mongo.auth.username | b64enc | quote }}
  password: {{ .Values.mongo.auth.password | b64enc | quote }}
  uri: {{ printf "mongodb://%s:%s@%s:%s" .Values.mongo.auth.username .Values.mongo.auth.password "re-id-mongo" "27017" | b64enc | quote }}