apiVersion: v1
kind: Service
metadata:
  name: re-id-mongo
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: re-id-mongo
  ports:
    - name: tcp-27017
      port: {{ .Values.mongo.service.port }}
      protocol: TCP
      targetPort: {{ .Values.mongo.service.port }}
