apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: re-id-mongo
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: re-id-mongo
  replicas: 1
  selector:
    matchLabels:
      app: re-id-mongo
  template:
    metadata:
      labels:
        app: re-id-mongo
    spec:
      containers:
        - name: mongo
          image: "{{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag }}"
          imagePullPolicy: {{ .Values.mongo.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.mongo.service.port }}
              name: mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: re-id-mongo
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: re-id-mongo
                  key: password
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          resources:
            {{- toYaml .Values.mongo.resources | nindent 12 }}
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: re-id-mongo
