---
apiVersion: v1
kind: Service
metadata:
  name: re-identification-system
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    application: re-identification-system
  ports:
    - name: http
      port: 80
      targetPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: re-identification-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    application: re-identification-service
  ports:
    - name: http
      port: 80
      targetPort: 5000