apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: re-identification-system
  namespace: {{ .Release.Namespace }}
spec:
  gateways:
    - teknoir/teknoir-gateway
  hosts:
    - '*'
  http:
    - match:
        - uri:
            prefix: /re-identification-system/matching-service
      route:
        - destination:
            host: matching-service.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 80
    - match:
        - uri:
            prefix: /re-identification-system/manifest-editor
      route:
        - destination:
            host: manifest-editor.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 80
    - match:
        - uri:
            prefix: {{ .Values.basePath | quote }}
      route:
        - destination:
            host: re-identification-system.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 80
